# fly.toml app configuration file generated for shorten on 2023-12-04T18:02:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shorten"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
